version: "3.3"
services:
  jobatator:
    image: lefuturiste/jobatator
    container_name: jobatator_unit_test
    restart: "no"
    ports:
      - "8962:8962"
    volumes:
      - "./jobatator.unit-test.config.yml:/go/src/app/config.yml"
  jobatator-php:
      build: ./
      restart: "no"
      environment:
        - JOBATATOR_HOST=jobatator
      links:
        - jobatator:jobatator
      depends_on:
        - jobatator